language: python
os: linux

cache:
  directories:
    - hrenv

before_install:
  - pip install hererocks
  - hererocks hrenv --luarocks=latest --lua=5.3
  - source hrenv/bin/activate

install:
  - luarocks install busted
  - luarocks install luacheck
  - luarocks make # This installs necessary runtime dependencies

before_script:
  - make linux-noreadline

script:
  - luacheck ./pallene ./spec ./examples
  - busted -o gtest -v ./spec


